apiVersion: apps/v1
kind: Deployment 
metadata:
  name: boardgame
spec:
  selector:
  matchLabels: 
    app: boardgame
  replicas: 2
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: mooo653/BoardGame
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: boardgame
spec:
  type: LoadBalancer
  selector:
    app: boardgame
  ports:
    - port: 8080
      targetPort: 8080
